name: Hackathon Voting System Checks

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    unitTest:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Install Dependencies
              run: |
                  cd NextJS
                  npm install
            - name: Run Tests
              run: |
                  cd NextJS
                  npm run test:unit

    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Install Dependencies
              run: |
                  cd NextJS
                  npm install
            - name: Lint code with ESLint
              run: |
                  cd NextJS
                  npm run lint

    format:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Install Dependencies
              run: |
                  cd NextJS
                  npm install
            - name: Format code with Prettier
              run: |
                  cd NextJS
                  npm run format:check
    deploy:
        needs: [unitTest, lint, format]
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create Pull Request
              id: pr
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: production
                  commit-message: |
                      Automated PR
                  title: |
                      Automated Pull Request
                  body: |
                      This pull request was automatically generated from the 'main' branch to 'production'.
                      Latest commit:
                      ${{ github.event.head_commit.message }}
